export const CONTENT_LOADED = 'CONTENT_LOADED';
export const APPLICATION_READY = 'APPLICATION_READY';

export const RESET_FOCUS = 'RESET_FOCUS';
export const MOVE_DISPATCHED = 'MOVE_DISPATCHED';

export const DISPATCH_MOVE = 'DISPATCH_MOVE';